version: '3'
services:
  
  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    depends_on:
      - mysql
    container_name: nodeserver
    ports:
      - "8000:8000"
    volumes:
      - "./server:/app/src"
    command: "npx nodemon server.js"

  mysql:
    image: mysql:5.7.31
    container_name: mysqldb
    ports:
      - "3306:3306"
    environment:
      MYSQL_PASSWORD: "root"
